services:
  postgres:
    image: postgres:15
    container_name: nestjs-postgres
    restart: always
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # 선택사항: pgAdmin (PostgreSQL 관리 도구)
  pgadmin:
    image: dpage/pgadmin4
    container_name: nestjs-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${DB_ADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_ADMIN_PORT}:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge